In [1]:
import numpy as np

In [2]:
# square vs. rectangular
S = np.random.randint(10, size=(5,5))
R = np.random.randint(10, size=(5,2)) # 5 rows, 2 columns

print("Square Matrix: \n", S), print(' ')
print("Rectangular Matrix: \n", R)

# identity matrix
I = np.eye(3)   # as idenetity matrix alwayas be a square matrix so we don't need to write 3, 3 or 2, 2
print("Identity Matrix: \n", I), print(' ')

# zeros matrix
""" here we put tupple (4, 4) beacuse if we put 4,4 i will through error as the zeroes function looking for
first input to be the sizes and second input to be the data type
for example:
Z = np.zeros((4, 4), dtype="complex")
So if write np.zeros(4, 4) it will take second 4 as data type and because 4 is not data type so error occurs"""
# Z = np.zeros((4, 4), dtype="complex")
# print(Z), print(' ')

Z = np.zeros((4,4))
print("Zero Matrix: \n", Z), print(' ')

# diagonal matrix
D = np.diag([ 1, 2, 3, 5, 2 ])
print("Diagonal Matrix: \n", D), print(' ')

# create triangular matrix from full matrices
S = np.random.randint(10, size=(5,5))
print("Full matrix: \n", S), print(' ')
U = np.triu(S)   # upper
L = np.tril(S)   # lower
print("Upper triangular Matrix: \n", U), print(' ')
print("Lower triangular Matrix: \n", L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randint(10, size=(3,2))
B = np.random.randint(10, size=(3,4))

C = np.concatenate((A,B),axis=1)   # axis=1 concatinate the martix horizontally
print("Augmented Matrix: \n", C)

Square Matrix: 
 [[3 3 6 0 5]
 [0 4 8 0 3]
 [1 6 4 4 8]
 [9 4 5 8 7]
 [4 3 5 3 4]]
 
Rectangular Matrix: 
 [[8 5]
 [5 7]
 [2 2]
 [2 8]
 [7 9]]
Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
Zero Matrix: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
Diagonal Matrix: 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
Full matrix: 
 [[5 2 7 8 8]
 [0 3 4 6 5]
 [5 7 5 6 8]
 [5 2 1 2 3]
 [7 1 8 2 1]]
 
Upper triangular Matrix: 
 [[5 2 7 8 8]
 [0 3 4 6 5]
 [0 0 5 6 8]
 [0 0 0 2 3]
 [0 0 0 0 1]]
 
Lower triangular Matrix: 
 [[5 0 0 0 0]
 [0 3 0 0 0]
 [5 7 5 0 0]
 [5 2 1 2 0]
 [7 1 8 2 1]]
 
Augmented Matrix: 
 [[2 9 8 5 3 0]
 [6 8 1 5 7 1]
 [6 7 8 7 8 7]]


# Matrix addition and subtraction

In [3]:
# create random matrices
A = np.random.randint(10, size=(5,4))
B = np.random.randint(10, size=(5,3))
C = np.random.randint(10, size=(5,4))

print("Matrix A: \n", A)
print()
print("Matrix B: \n", B)
print()
print("Matrix C: \n", C)
print()

# try to add them
# A+B     # produce error
try:
    print("Matrix A + Matrix B: \n", A+B)
except Exception as e:
    print("Matrix A + Matrix B: ", e)
print()

print("Matrix A + Matrix C: \n", A+C)
print()

# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randint(10, size=(N,N)) # can only shift a square matrix

Ds = D + l*np.eye(N)
print("Original Matrix: \n", D), print(' '), print("Shifted Matrix: \n", Ds)

Matrix A: 
 [[7 8 0 2]
 [9 1 9 4]
 [6 1 9 5]
 [0 4 7 4]
 [0 6 7 0]]

Matrix B: 
 [[6 9 2]
 [9 8 8]
 [8 3 9]
 [4 1 6]
 [0 8 6]]

Matrix C: 
 [[3 2 6 9]
 [3 8 0 3]
 [2 4 1 2]
 [5 1 0 0]
 [3 5 7 9]]

Matrix A + Matrix B:  operands could not be broadcast together with shapes (5,4) (5,3) 

Matrix A + Matrix C: 
 [[10 10  6 11]
 [12  9  9  7]
 [ 8  5 10  7]
 [ 5  5  7  4]
 [ 3 11 14  9]]

Original Matrix: 
 [[3 6 5 1 5]
 [5 6 2 2 7]
 [1 8 5 7 8]
 [1 1 2 5 1]
 [7 8 9 4 7]]
 
Shifted Matrix: 
 [[3.03 6.   5.   1.   5.  ]
 [5.   6.03 2.   2.   7.  ]
 [1.   8.   5.03 7.   8.  ]
 [1.   1.   2.   5.03 1.  ]
 [7.   8.   9.   4.   7.03]]


(None, None, None)

# Matrix-scalar multiplication

In [4]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
print("Original Matrix: \n", M)
s = 2
print()

# pre- and post-multiplication is the same:
print(f"Pre multiplication of Matrix with scalar s={s}: \n", M*s)
print()
print(f"post multiplication of Matrix with scalar s={s}: \n", s*M )

Original Matrix: 
 [[1 2]
 [2 5]]

Pre multiplication of Matrix with scalar s=2: 
 [[ 2  4]
 [ 4 10]]

post multiplication of Matrix with scalar s=2: 
 [[ 2  4]
 [ 4 10]]


In [5]:
# Code practice 1:
# test for some random MxN matrices whether s(A+B) = sA + sB
"""Distributivity"""

A = np.random.randint(10, size=(5,4))
B = np.random.randint(10, size=(5,4))

print("Matrix A: \n", A)
print()
print("Matrix B: \n", B)
print()

s = np.random.randint(10)
print("Scalar s = ", s)
print()

print("s(A+B) = \n", s*(A+B))
print()

print("sA + sB = \n", (s*A + s*B))

Matrix A: 
 [[6 7 5 8]
 [9 1 0 5]
 [9 7 0 0]
 [6 9 7 8]
 [0 6 3 0]]

Matrix B: 
 [[6 5 5 0]
 [4 1 7 5]
 [1 4 7 9]
 [4 1 8 6]
 [3 3 8 1]]

Scalar s =  1

s(A+B) = 
 [[12 12 10  8]
 [13  2  7 10]
 [10 11  7  9]
 [10 10 15 14]
 [ 3  9 11  1]]

sA + sB = 
 [[12 12 10  8]
 [13  2  7 10]
 [10 11  7  9]
 [10 10 15 14]
 [ 3  9 11  1]]


# Transpose of a Matrix

In [6]:
M = np.random.randint(10, size=(2,3))
print("Matrix M: \n", M)
print()
print("Transpose of Matrix M: \n", M.T)
print()
print("Transpose of Transpose of Matrix M (M''): \n", M.T.T)
print()

# can also use the transpose function
# print(np.transpose(M))

Matrix M: 
 [[4 3 7]
 [4 4 2]]

Transpose of Matrix M: 
 [[4 4]
 [3 4]
 [7 2]]

Transpose of Transpose of Matrix M (M''): 
 [[4 3 7]
 [4 4 2]]



In [7]:
# Creating a Matrix of random complex numbers
M = np.random.randint(10, size=(5,5)) + np.random.randint(10, size=(5,5)) * 1j
print("Matrix M: \n", M)
print()
print("Transpose of Matrix M: \n", M.T)
print()

# Hermition transpose of Matrix
print("Hermition Transpose of Matrix M: \n", np.matrix(M).H)  # first converting the numpy array to a matrix object
print()

Matrix M: 
 [[2.+8.j 0.+1.j 0.+5.j 9.+3.j 1.+0.j]
 [8.+4.j 9.+9.j 8.+8.j 2.+9.j 9.+0.j]
 [1.+9.j 7.+6.j 5.+6.j 3.+0.j 4.+8.j]
 [3.+2.j 4.+8.j 2.+7.j 7.+9.j 8.+8.j]
 [1.+7.j 8.+0.j 5.+3.j 6.+1.j 0.+3.j]]

Transpose of Matrix M: 
 [[2.+8.j 8.+4.j 1.+9.j 3.+2.j 1.+7.j]
 [0.+1.j 9.+9.j 7.+6.j 4.+8.j 8.+0.j]
 [0.+5.j 8.+8.j 5.+6.j 2.+7.j 5.+3.j]
 [9.+3.j 2.+9.j 3.+0.j 7.+9.j 6.+1.j]
 [1.+0.j 9.+0.j 4.+8.j 8.+8.j 0.+3.j]]

Hermition Transpose of Matrix M: 
 [[2.-8.j 8.-4.j 1.-9.j 3.-2.j 1.-7.j]
 [0.-1.j 9.-9.j 7.-6.j 4.-8.j 8.-0.j]
 [0.-5.j 8.-8.j 5.-6.j 2.-7.j 5.-3.j]
 [9.-3.j 2.-9.j 3.-0.j 7.-9.j 6.-1.j]
 [1.-0.j 9.-0.j 4.-8.j 8.-8.j 0.-3.j]]



# Diagonal and Trace

In [8]:
# M = np.round(np.random.randn(4,4))
M = np.random.randint(10, size=(5,5))
print("Original Matrix: \n", M), print(' ')

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print("Matrix-(I) --> Vector-(O)\n", d)
print()
print("Vector-(I) --> Matrix-(O)\n", D)
print()

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum(np.diag(M))
print("Trace of a Matrix: ", tr,tr2)

Original Matrix: 
 [[7 5 9 2 0]
 [7 4 0 7 4]
 [0 9 6 4 5]
 [6 0 2 1 4]
 [0 3 5 3 8]]
 
Matrix-(I) --> Vector-(O)
 [7 4 6 1 8]

Vector-(I) --> Matrix-(O)
 [[7 0 0 0 0]
 [0 4 0 0 0]
 [0 0 6 0 0]
 [0 0 0 1 0]
 [0 0 0 0 8]]

Trace of a Matrix:  26 26


In [9]:
# Code Practice 2:
# Determine the linearity of Trace i.e., tr(A+B) = tr(A) + tr(B)
# and check tr(l*A) vs l*tr(A)

""" Let's start """

A = np.random.randint(10, size=(5,5))
B = np.random.randint(10, size=(5,5))

print("Matrix A: \n", A), print(' ')
print("Matrix B: \n", B), print(' ')

print("Trace(A+B) \n", np.trace(A+B))
print()
print("Trace(A) + Trace(B) \n", (np.trace(A)+np.trace(B)))
print()

print("Trace(l*A) \n", np.trace(2*A))
print()
print("l*Trace(A) \n", (2*np.trace(A)))



Matrix A: 
 [[0 2 7 6 3]
 [4 6 5 5 1]
 [4 1 0 5 3]
 [4 8 0 7 5]
 [3 7 0 5 5]]
 
Matrix B: 
 [[3 4 0 6 3]
 [7 7 3 3 4]
 [8 5 6 2 1]
 [9 5 1 8 0]
 [3 0 3 2 9]]
 
Trace(A+B) 
 51

Trace(A) + Trace(B) 
 51

Trace(l*A) 
 36

l*Trace(A) 
 36


# Broadcasting matrix arithmetic

In [10]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')     # Used as Row vector
print(c), print(' ')     # Used as Column vector

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


(None, None)

In [11]:
""" Broadcasting """
# broadcast on the rows
print(A+r), print(' ')

# broadcast on the columns
# print(A+c)
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
