In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

# Computing rank

In [2]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randint(10, size=(m,n))
print("Matrix A: \n", A)
print()

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('Rank(A) = ' + str(ra))
print()

# set last column to be repeat of penultimate column(second last column)
B = A
B[:,-1] = B[:,-2]
print("Matrx B(modified A): \n", B)
print()

rb = np.linalg.matrix_rank(B)
print('rank(B) = ' + str(rb))
print()

# set last row to be repeat of penultimate row(second last row)
B = A
B[-1, :] = B[-2, :]
print("Matrx B(modified A): \n", B)
print()

rb = np.linalg.matrix_rank(B)
print('rank(B) = ' + str(rb))

Matrix A: 
 [[2 1 8 8 6 3]
 [4 5 4 5 9 7]
 [9 4 8 0 6 3]
 [7 4 8 8 5 4]]

Rank(A) = 4

Matrx B(modified A): 
 [[2 1 8 8 6 6]
 [4 5 4 5 9 9]
 [9 4 8 0 6 6]
 [7 4 8 8 5 5]]

rank(B) = 4

Matrx B(modified A): 
 [[2 1 8 8 6 6]
 [4 5 4 5 9 9]
 [9 4 8 0 6 6]
 [9 4 8 0 6 6]]

rank(B) = 3


In [3]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.random.randint(10, size=(m,m))


# reduce the rank
A[:,-1] = A[:,-2]
print("Matrix A: \n", A)
print()

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)
print("Matrix B(adding noise to A): \n", B)
print()

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))

Matrix A: 
 [[6 4 0 0]
 [4 3 1 1]
 [8 2 2 2]
 [9 8 6 6]]

Matrix B(adding noise to A): 
 [[6.00005978e+00 3.99917725e+00 1.33063527e-03 1.35295774e-04]
 [4.00034116e+00 3.00073296e+00 9.98787328e-01 1.00001253e+00]
 [8.00000940e+00 2.00181732e+00 1.99980405e+00 2.00242243e+00]
 [8.99947512e+00 8.00049338e+00 6.00021353e+00 6.00037309e+00]]

rank (w/o noise) = 3
rank (with noise) = 4


In [4]:
# Code Practice 1: Code Problem: Reduce-Rank using matrix multiplication
# Q = Create a 10x10 matrix of r=4 using matrix multiplication

# first create two matrices asuuming that they will full(column/row) rank matrices
A = np.random.randint(10, size=(10,4))
B = np.random.randint(10, size=(4,10))

C = A@B
print("Shape of C = ", np.shape(C))
print("Rank of C = ", np.linalg.matrix_rank(C))

# generalize the above procedure for any mxn matrix with rank r
m = 8
n = 7
# rank should be the min of m, n i.e., rank <= min(m, n)
r = 5

A = np.random.randint(10, size=(m,r))
B = np.random.randint(10, size=(r,n))


# C will be mxn matrix with rank r
C = A@B
print("Shape of C = ", np.shape(C))
print("Rank of C = ", np.linalg.matrix_rank(C))

Shape of C =  (10, 10)
Rank of C =  4
Shape of C =  (8, 7)
Rank of C =  5


In [5]:
# Code Practice 2: Scalar multiplication and rank

# test whether the matrix rank is invariant to scalar multiplication

# create two matrices a full(column/row) rank and a reduce-rank
m = 7
n = 5

F = np.random.randint(10, size=(m,n)) @ np.random.randint(10, size=(n,n))
R = np.random.randint(10, size=(m,n-1)) @ np.random.randint(10, size=(n-1,n))

# create some scalar axcept 0
l = 2927894

# print rank of F and R, l*F, l*R
print('rank(F) = ' + str(np.linalg.matrix_rank(F)))
print('rank(l*F) = ' + str(np.linalg.matrix_rank(l*F)))
print('rank(R) = ' + str(np.linalg.matrix_rank(R)))
print('rank(l*R) = ' + str(np.linalg.matrix_rank(l*R)))


rank(F) = 5
rank(l*F) = 5
rank(R) = 4
rank(l*R) = 4


# Rank of A^TA and AA^T

In [6]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round(10*np.random.randn(m,n))

At = A.T
AtA = A.T@A
AAt = A@A.T

# get matrix sizes
sizeA = AtA.shape
sizeAt = AtA.shape
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('A: %dx%d, rank=%d' %(sizeA[0], sizeA[1], np.linalg.matrix_rank(A)))
print('At: %dx%d, rank=%d' %(sizeAt[0], sizeAt[1], np.linalg.matrix_rank(At)))
print('AtA: %dx%d, rank=%d' %(sizeAtA[0], sizeAtA[1], np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0], sizeAAt[1], np.linalg.matrix_rank(AAt)))

A: 3x3, rank=3
At: 3x3, rank=3
AtA: 3x3, rank=3
AAt: 14x14, rank=3


# Making a matrix full-rank by "shifting"

In [7]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round(10*(A.T@A))

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))

rank(w/o shift) = 29
rank(with shift) = 30


In [8]:
# Code Practice 1: Is the vector in the span of of this set

# determine wether this vector
V = np.array([[1, 2, 3, 4]]).T
print("Vector V: \n", V)
print()
# is in the span of these sets ?
S = np.vstack(([4, 3, 6, 2], [0, 4, 0, 1])).T
T = np.vstack(([1, 2, 2, 2], [0, 0, 1, 2])).T
print("Matrix S: \n", S)
print()
print("Matrix T: \n", T)
print()

"""
if Vector V is contained in the span in the subspace spend by set s,
then putting Vector V into this set is going to create a linearly 
dependent set of vectors as the algebraic way 
geometrically Vector V does not expand the dimensionality of 
the space that is spanned by set s. 
So the dimensionality will still the same.
"""

SV = np.concatenate((S,V), axis=1)
TV = np.concatenate((T,V), axis=1)

print("Matrix [S, V]: \n", SV)
print()
print("Matrix [T, V]: \n", TV)
print()
print("Rank of [S, V]", np.linalg.matrix_rank(SV))
print("Rank of [T, V]", np.linalg.matrix_rank(TV))

Vector V: 
 [[1]
 [2]
 [3]
 [4]]

Matrix S: 
 [[4 0]
 [3 4]
 [6 0]
 [2 1]]

Matrix T: 
 [[1 0]
 [2 0]
 [2 1]
 [2 2]]

Matrix [S, V]: 
 [[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]

Matrix [T, V]: 
 [[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]

Rank of [S, V] 3
Rank of [T, V] 2
